name: fsvod
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pytorch=1.12.1
  - torchvision=0.13.1
  - cudatoolkit=11.3.1  # Use appropriate CUDA version for your system
  - numpy=1.24.4
  - opencv=4.5.5
  - pip
  - pip:
    - opencv-python==4.5.5.64
    - pyyaml
    - tqdm
    - matplotlib
    - scikit-learn
    - tensorboard
    - pandas
    - pillow
    - scipy
    - seaborn
